# OpenChargeback CI/CD Pipeline
# Runs tests on every push, deploys to projects.xram.net on main
#
# Pip cache mounted at /opt/cache/pip for faster builds

steps:
  - name: test-and-lint
    image: python:3.12-slim
    commands:
      - apt-get update && apt-get install -y --no-install-recommends git
      - pip install --cache-dir /cache/pip -e ".[dev]"
      - ruff check src/
      - pytest -v --tb=short
    volumes:
      - /opt/cache/pip:/cache/pip

  - name: typecheck
    image: python:3.12-slim
    commands:
      - pip install --cache-dir /cache/pip -e ".[dev]" types-PyYAML
      - mypy src/ --ignore-missing-imports
    volumes:
      - /opt/cache/pip:/cache/pip
    failure: ignore  # Don't fail build on type errors (yet)

  - name: sbom
    image: python:3.12-slim
    commands:
      - pip install --cache-dir /cache/pip cyclonedx-bom
      - pip install --cache-dir /cache/pip -e .
      - cyclonedx-py environment --of json -o src/openchargeback/web/static/sbom.json
    volumes:
      - /opt/cache/pip:/cache/pip
    when:
      branch: main
    depends_on:
      - test-and-lint

  - name: deploy
    image: docker:cli
    commands:
      - cd /projects/${CI_REPO_NAME} || git clone ${CI_REPO_CLONE_URL} /projects/${CI_REPO_NAME}
      - cd /projects/${CI_REPO_NAME} && git fetch && git checkout ${CI_COMMIT_BRANCH} && git pull
      - cd /projects/${CI_REPO_NAME} && docker compose up -d --build
      - docker image prune -f
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/projects:/projects
    when:
      branch: main
    depends_on:
      - sbom
